export const columnDefinitions = {
    order_booked: [
        { key: 'sales_person', label: 'Sales Person', sortable: true },
        { key: 'client_name', label: 'Client Name/Account Name', sortable: true },
        { key: 'opportunity_name', label: 'Opportunity Name', sortable: true },
        { key: 'products_services', label: 'Products/Services Pitched', sortable: true },
        { key: 'mrr', label: 'MRR (Cr.)', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'acv', label: 'ACV (Cr.)', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'otc', label: 'OTC (Cr.)', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'project_tenure', label: 'Project Tenure', sortable: true },
        { key: 'tcv', label: 'TCV (Cr.)', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'sales_stage', label: 'Sales Stage (L1-L6)', sortable: true },
        { key: 'stage_description', label: 'Stage Description', sortable: true },
        { key: 'probability', label: 'Probability %', sortable: true, render: (val) => val ? `${val}%` : '-' },
        { key: 'expected_closer_date', label: 'Expected Closer Date', sortable: true },
        { key: 'quarter', label: 'Quarter (Q1-Q4)', sortable: true },
        { key: 'sales_type', label: 'Sales Type', sortable: true }
    ],
    payment_collection: [
        { key: 'sales_person_name', label: 'Sales Person Name', sortable: true },
        { key: 'client_id', label: 'Client ID', sortable: true },
        { key: 'client_name', label: 'Client Name', sortable: true },
        { key: 'invoice_amount', label: 'Invoice Amount', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'received_amount', label: 'Received Amount', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'tds', label: 'TDS', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' }
    ],
    funnel: [
        { key: 'date', label: 'Date', sortable: true },
        { key: 'opportunity_owner_name', label: 'Opportunity Owner Name', sortable: true },
        { key: 'organisation_name', label: 'Organisation Name', sortable: true },
        { key: 'partner_organisation', label: 'Partner Organisation', sortable: true },
        { key: 'what_selling', label: 'What are we selling here', sortable: true },
        { key: 'opportunity_id', label: 'Opportunity Id', sortable: true },
        { key: 'tender_type', label: 'Tender/Non Tender', sortable: true },
        { key: 'sales_stages', label: 'Sales Stages (L1 to L5)', sortable: true },
        { key: 'contact_name', label: 'Contact Name', sortable: true },
        { key: 'email', label: 'Email', sortable: true },
        { key: 'remark', label: 'Remark', sortable: true }
    ],
    proposal_submitted: [
        { key: 'date', label: 'Date', sortable: true },
        { key: 'pot_id', label: 'POT ID', sortable: true },
        { key: 'source', label: 'Source', sortable: true },
        { key: 'sales_person', label: 'Sales Person', sortable: true },
        { key: 'client_name', label: 'Client Name/Account Name', sortable: true },
        { key: 'opportunity_name', label: 'Opportunity Name', sortable: true },
        { key: 'mrr', label: 'MRR', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'acv', label: 'ACV', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'otc', label: 'OTC', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'project_tenure', label: 'Project Tenure', sortable: true },
        { key: 'tcv', label: 'TCV', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'sales_stage', label: 'Sales Stage (L1-L6)', sortable: true },
        { key: 'stage_description', label: 'Stage Description', sortable: true },
        { key: 'probability', label: 'Probability %', sortable: true, render: (val) => val ? `${val}%` : '-' },
        { key: 'sales_type', label: 'Sales Type', sortable: true },
        { key: 'industry', label: 'Industry', sortable: true },
        { key: 'region', label: 'Region', sortable: true },
        { key: 'channel_manager', label: 'Channel/Alliance Manager Name', sortable: true },
        { key: 'remark', label: 'Remark', sortable: true },
        { key: 'latest_remark', label: 'Latest Remark', sortable: true }
    ],
    demos: [
        { key: 'sales_person', label: 'Sales Person', sortable: true },
        { key: 'client_name', label: 'Client Name/Account Name', sortable: true },
        { key: 'demo_product_name', label: 'Demo Product Name', sortable: true },
        { key: 'sales_stage', label: 'Sales Stage (L1-L6)', sortable: true },
        { key: 'stage_description', label: 'Stage Description', sortable: true },
        { key: 'probability', label: 'Probability %', sortable: true, render: (val) => val ? `${val}%` : '-' },
        { key: 'region', label: 'Region', sortable: true },
        { key: 'client_spoc', label: 'Name of Client Spoc/Email ID & Contact Number', sortable: true },
        { key: 'contact_no', label: 'Contact No.', sortable: true },
        { key: 'email_id', label: 'Email ID', sortable: true }
    ],
    partner_on_board: [
        { key: 'date', label: 'Date', sortable: true },
        { key: 'sales_person', label: 'Sales Person', sortable: true },
        { key: 'client_name', label: 'Client Name/Account Name', sortable: true },
        { key: 'products', label: 'Products', sortable: true },
        { key: 'remark', label: 'Remark', sortable: true },
        { key: 'contact_person_name', label: 'Contact Person Name', sortable: true },
        { key: 'contact_no', label: 'Contact No', sortable: true },
        { key: 'email_id', label: 'Email ID', sortable: true }
    ],
    client_direct_visit: [
        { key: 'date', label: 'Date', sortable: true },
        { key: 'sales_person', label: 'Sales Person', sortable: true },
        { key: 'client_name', label: 'Client Name/Account Name', sortable: true },
        { key: 'products_services_pitched', label: 'Products/Services Pitched', sortable: true },
        { key: 'industry', label: 'Industry', sortable: true },
        { key: 'region', label: 'Region', sortable: true }
    ],
    dc_visit: [
        { key: 'date', label: 'Date', sortable: true },
        { key: 'sales_person', label: 'Sales Person', sortable: true },
        { key: 'account_client_name', label: 'Account/Client Name', sortable: true },
        { key: 'product_pitched_in', label: 'Product Pitched in', sortable: true },
        { key: 'sector', label: 'Sector', sortable: true },
        { key: 'region', label: 'Region', sortable: true },
        { key: 'contact_person', label: 'Contact Person', sortable: true },
        { key: 'email_id', label: 'Email ID', sortable: true },
        { key: 'mobile_number', label: 'Mobile Number', sortable: true }
    ],
    events_attend: [
        { key: 'sales_person', label: 'Sales Person', sortable: true },
        { key: 'event_name', label: 'Event Name', sortable: true },
        { key: 'organised_by', label: 'Organised by', sortable: true },
        { key: 'topic', label: 'Topic', sortable: true },
        { key: 'venue', label: 'Venue', sortable: true },
        { key: 'date', label: 'Date', sortable: true },
        { key: 'to', label: 'To', sortable: true },
        { key: 'total_client_visited', label: 'Total Client Visited', sortable: true },
        { key: 'total_delegates_attended', label: 'Total Delegates Attended', sortable: true }
    ],
    tender: [
        { key: 'date', label: 'Date', sortable: true },
        { key: 'pot_id', label: 'POT Id', sortable: true },
        { key: 'who_working', label: 'Who Working', sortable: true },
        { key: 'url', label: 'URL', sortable: true },
        { key: 'customer_name', label: 'Customer Name', sortable: true },
        { key: 'tender_name', label: 'Tender Name', sortable: true },
        { key: 'published_date', label: 'Published Date', sortable: true },
        { key: 'last_date_purchase_rfp', label: 'Last Date Purchase RFP', sortable: true },
        { key: 'last_date_submit_pre_bid', label: 'Last Date Submit Pre Bid Queries', sortable: true },
        { key: 'pre_bid_date', label: 'Pre-Bid Date', sortable: true },
        { key: 'submission_date', label: 'Submission Date', sortable: true },
        { key: 'technical_tender_opening', label: 'Technical Tender Opening Date', sortable: true },
        { key: 'commercial_tender_opening', label: 'Commercial Tender Opening Date', sortable: true },
        { key: 'tender_fee', label: 'Tender Fee', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'emd', label: 'EMD', sortable: true, render: (val) => val ? `Rs ${Number(val).toFixed(2)}` : '-' },
        { key: 'bank_guarantee_percentage', label: 'Bank Guarantee Percentage', sortable: true },
        { key: 'contact_person', label: 'Contact Person', sortable: true },
        { key: 'contact_no', label: 'Contact No.', sortable: true },
        { key: 'email_id', label: 'Email ID', sortable: true },
        { key: 'submission_address', label: 'Submission Address', sortable: true },
        { key: 'account_manager', label: 'Account Manager', sortable: true },
        { key: 'submitted', label: 'Submitted (Yes/No)', sortable: true },
        { key: 'not_submitted_remark', label: 'if Not Submitted Remark', sortable: true }
    ],
    daily_report: [
        { key: 'date', label: 'Date', sortable: true },
        { key: 'employee_name', label: 'Employee Name', sortable: true },
        { key: 'leads_received_from', label: 'Leads Received From', sortable: true },
        { key: 'nature', label: 'Nature', sortable: true },
        { key: 'new_existing_lead', label: 'New/Existing Lead', sortable: true },
        { key: 'tender_opportunity_details', label: 'Tender/Opportunity Details', sortable: true },
        { key: 'bank_company_name', label: 'Bank/Cr.Soc./Company Name', sortable: true },
        { key: 'solutions_products', label: 'Solutions/Products', sortable: true },
        { key: 'person_name', label: 'Person Name', sortable: true },
        { key: 'designation', label: 'Designation', sortable: true },
        { key: 'contact_no', label: 'Contact No', sortable: true },
        { key: 'email_id', label: 'Email Id', sortable: true },
        { key: 'address', label: 'Address', sortable: true },
        { key: 'state', label: 'State', sortable: true },
        { key: 'product_interested_in', label: 'Product Interested In', sortable: true },
        { key: 'next_action', label: 'Next Action', sortable: true },
        { key: 'next_follow_up_date', label: 'Next Follow up Date', sortable: true }
    ]
};
